version: "3.3"

services:
  vultr:
    build:
      context: /home/rom/apps/vultrapi/
    container_name: vultrapi
    restart: always
    user: 1000:985
    volumes:
      - /home/rom/apps/vultrapi/:/home/vultr/vultr/vultr
    command: sh -c "/home/vultr/pyvenv/bin/python3 /home/vultr/vultr/vultr/main.py"

